version: '3.8'

services:
  auth:
    build: ./auth-service
    ports:
      - "8001:8001"

  product:
    build: ./product-service
    ports:
      - "8002:8002"

  order:
    build: ./order-service
    ports:
      - "8003:8003"
